name: shartflix_movie_app
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  dio: ^5.4.0
  args: ^2.4.2
  provider: ^6.1.3

    # Local storage dependencies
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Firebase dependencies
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^7.1.1
  flutter_secure_storage: ^9.0.0
  cloud_firestore: ^6.0.0



dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true